# Generated by Django 3.0.5 on 2020-07-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0004_auto_20200708_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanks',
            name='reward_exp',
            field=models.IntegerField(default=0),
        ),
    ]
