# Generated by Django 3.0.5 on 2020-07-11 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thanks', '0005_thanks_reward_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good_thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_thanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.Thanks')),
                ('thanks_good_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_good_giver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
