# Generated by Django 3.0.7 on 2020-06-27 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='cost_exp',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='mission',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_flg',
            field=models.IntegerField(choices=[(0, '実践中'), (1, '達成')], default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='participants_list',
            field=models.ManyToManyField(to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_giver', to=settings.AUTH_USER_MODEL)),
                ('good_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
            ],
        ),
    ]
