# Generated by Django 3.0.5 on 2020-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20200627_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='participants_list_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
