# Generated by Django 3.0.5 on 2020-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_mission_participants_list_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='approval',
            field=models.IntegerField(choices=[(0, '承認待ち'), (1, '承認済み')], default=0),
        ),
    ]
