# Generated by Django 3.0.5 on 2020-07-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thanks', '0005_thanks_reward_exp'),
        ('mission', '0004_mission_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good_mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_good_giver', to=settings.AUTH_USER_MODEL)),
                ('good_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Good_thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_good_giver', to=settings.AUTH_USER_MODEL)),
                ('good_thanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.Thanks')),
            ],
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
