# Generated by Django 3.0.5 on 2020-07-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_auto_20200711_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good_mission',
            old_name='good_giver',
            new_name='mission_good_giver',
        ),
        migrations.RenameField(
            model_name='good_thanks',
            old_name='good_giver',
            new_name='thanks_good_giver',
        ),
    ]
