# Generated by Django 3.0.5 on 2020-07-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_auto_20200712_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good_thanks',
        ),
    ]
