# Generated by Django 3.0.5 on 2020-07-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_delete_good_thanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='participants_limit',
            field=models.IntegerField(default=0),
        ),
    ]
