# Generated by Django 3.0.7 on 2020-06-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp_total',
            field=models.IntegerField(default=10, verbose_name='経験値'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kubun',
            field=models.CharField(blank=True, choices=[('1', '経営者'), ('2', '従業員')], max_length=2, verbose_name='区分'),
        ),
    ]
