# Generated by Django 3.0.5 on 2020-06-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200627_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_count',
            field=models.IntegerField(default=0),
        ),
    ]
