# Generated by Django 3.0.5 on 2020-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_success_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='success_count',
            new_name='my_success_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='team_success_count',
            field=models.IntegerField(default=0),
        ),
    ]
