# Generated by Django 3.0.5 on 2020-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200630_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kubun',
            field=models.CharField(blank=True, choices=[('1', '経営者'), ('2', '従業員'), ('3', '管理者')], max_length=2, verbose_name='区分'),
        ),
    ]
