# Generated by Django 3.0.5 on 2020-07-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200702_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_count',
            new_name='mission_create_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='thanked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='thanks_count',
            field=models.IntegerField(default=0),
        ),
    ]
